# Generated by Django 3.2 on 2025-08-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.municipality'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.ward'),
        ),
    ]
