# Generated by Django 3.2 on 2025-08-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250822_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='municipality',
        ),
    ]
