# Generated by Django 3.2 on 2025-08-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='training',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='municipality',
        ),
    ]
