# Generated by Django 3.2 on 2025-08-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20250822_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingregistration',
            name='registration_status',
        ),
        migrations.RemoveField(
            model_name='vacancyregistration',
            name='VacancyRegistration_status',
        ),
    ]
