# Generated by Django 3.2 on 2025-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20250822_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterStatus',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='image',
        ),
        migrations.AddField(
            model_name='training',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
